name: taskamo
description: Taskamo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.1+1
  flutter_launcher_icons: "^0.9.2"
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0
  flutter_native_splash: ^2.2.6
  graphql_flutter: ^5.1.0
  logger: ^1.1.0


#  flutter_localizations:
#  http: ^0.13.4
#  shamsi_date: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/

#  fonts:

