name: taskamo
description: Taskamo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.6
  flutter_launcher_icons: ^0.11.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0
  flutter_native_splash: ^2.2.6
  graphql_flutter: ^5.1.0
  logger: ^1.1.0
  localization: ^2.1.0
  flutter_localizations:
    sdk: flutter
  floating_bottom_navigation_bar: ^1.5.2
  dropdown_button2: ^1.8.2
  syncfusion_flutter_calendar: ^20.4.38
  #  table_calendar: ^3.0.8
#  calendar_view: ^1.0.1
#  http: ^0.13.4
#  shamsi_date: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/taskamo_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/
    - locale/

  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
        - asset: assets/fonts/nunito/Nunito-Light.ttf
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
        - asset: assets/fonts/nunito/Nunito-Black.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf